name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest] # TODO: fix windows and linux builds

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Node
      uses: actions/setup-node@master
      with:
        node-version: 12.18.4
        
    - name: Cache JavaScript dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: yarn-v1-${{ hashFiles('.node-version') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-v1-${{ hashFiles('.node-version') }}-

    - name: Install JavaScript dependencies
      run: yarn install

    - run: yarn run test
